add: check pr title

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -73,6 +73,12 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           pr_title="${{ github.event.pull_request.title }}"
+          if [[ ! $pr_title =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Invalid PR title format"
+            exit 1
+          else
+            echo "PR title format is valid"
+          fi
           pr_body=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'RC-\d+')
           git tag -a "$pr_title" -m "$pr_body"
           git push origin --tags
